services:
  - type: web
    name: gurukul-manager-backend
    env: python
    buildCommand: pip install -r backend/attendance_backend_firebase/requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:10000
    workingDirectory: backend/attendance_backend_firebase
    envVars:
      - key: FIREBASE_ADMIN_SDK_JSON
        value: serviceAccountKey.json