services:
  - type: web
    name: gurukul-manager-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend attendance_backend_firebase.app:app"
